import type { Command } from "commander";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { generateText } from "ai";
import { getProvider } from "../ai/provider.js";
import { readAgentPrompt } from "../lib/agents.js";
import { loadExerciseConfig, resolveTier, resolveTopic } from "../lib/config.js";
import { dateSlug, ensureDir, timestampSlug, writeTimestampedAndLatest } from "../lib/artifacts.js";
import { createPR, requireGithubEnv } from "../core/github.js";

const REVIEW_MODE_DIR = "exercises/review-mode";
const BOT_GIT_NAME = "AI Feature Writer";
const BOT_GIT_EMAIL = "gym-bot@ai-code-gym.local";

function runGit(args: string[], cwd: string): string {
  const result = spawnSync("git", args, { cwd, encoding: "utf-8" });
  if (result.error) {
    throw new Error(`ai-code-gym: failed to run "git ${args.join(" ")}": ${result.error.message}`);
  }
  if (result.status !== 0) {
    throw new Error(`ai-code-gym: "git ${args.join(" ")}" failed:\n${result.stderr}`);
  }
  return result.stdout.trim();
}

export function registerReviewNew(program: Command): void {
  program
    .command("review-new")
    .description("Generate a new buggy component for you to review (Review Mode)")
    .option("-t, --tier <1-4>", "difficulty tier, overrides exercise-config.json")
    .option("--topic <topic>", "exercise topic, overrides exercise-config.json")
    .action(async (opts: { tier?: string; topic?: string }) => {
      requireGithubEnv();

      const config = loadExerciseConfig();
      const tier = resolveTier(opts.tier, config);
      const topic = resolveTopic(opts.topic, config);

      const systemPrompt = readAgentPrompt("feature-writer");
      const { name: providerName, model } = getProvider();

      const userPrompt = `
Write a React + TypeScript component for a "${topic}" exercise at difficulty tier ${tier}.
The component should be realistic, roughly 60-120 lines, and contain the appropriate number and type of intentional bugs for tier ${tier}.
Include the hidden <!-- BUGS --> manifest at the end of your response.
`.trim();

      console.log(`Generating tier-${tier} ${topic} review exercise via ${providerName}...`);
      const { text } = await generateText({
        model,
        system: systemPrompt,
        prompt: userPrompt,
        maxOutputTokens: 4096,
      });

      const parts = text.split("<!-- BUGS -->");
      const codePart = parts[0] ?? text;
      const bugPart = parts[1];
      const codeMatch = codePart.match(/```(?:tsx?)?\n([\s\S]*?)```/);
      const code = codeMatch?.[1] ?? codePart.trim();

      await ensureDir(REVIEW_MODE_DIR);
      const timestamp = dateSlug();
      const exerciseFileName = `exercise-${timestamp}-${topic}.tsx`;

      // The bug manifest is the answer key — it must never be committed to the branch the
      // bot pushes, since that branch becomes a public PR the reviewer (you) will read.
      await Promise.all([
        writeTimestampedAndLatest(REVIEW_MODE_DIR, exerciseFileName, "latest-exercise.tsx", code),
        writeFile(
          path.join(REVIEW_MODE_DIR, "latest-bug-manifest.json"),
          JSON.stringify({ raw: bugPart?.trim() ?? "" }, null, 2),
        ),
      ]);

      const repoDir = process.cwd();
      const originalBranch = runGit(["rev-parse", "--abbrev-ref", "HEAD"], repoDir);
      const branchName = `gym/review-${topic}-${timestampSlug()}`;

      console.log(`Committing the exercise and opening a PR as the "${BOT_GIT_NAME}" bot...`);
      let branchCreated = false;
      try {
        runGit(["checkout", "-b", branchName], repoDir);
        branchCreated = true;
        runGit(
          ["add", path.join(REVIEW_MODE_DIR, exerciseFileName), path.join(REVIEW_MODE_DIR, "latest-exercise.tsx")],
          repoDir,
        );
        runGit(
          [
            "-c",
            `user.name=${BOT_GIT_NAME}`,
            "-c",
            `user.email=${BOT_GIT_EMAIL}`,
            "commit",
            "-m",
            `Review Mode: tier ${tier} ${topic} exercise`,
          ],
          repoDir,
        );
        runGit(["push", "-u", "origin", branchName], repoDir);
      } finally {
        // However far the sequence above got, never leave the user stranded on the
        // throwaway branch — always try to restore whatever branch they started on.
        if (branchCreated) {
          runGit(["checkout", originalBranch], repoDir);
        }
      }

      const pr = await createPR(
        branchName,
        `Review Mode: tier ${tier} — ${topic}`,
        `Auto-generated by the AI Feature Writer for a tier-${tier} "${topic}" review exercise.\n\n` +
          `Review the changed file in this PR like a real code review and leave your comments as PR review ` +
          `comments. When you're done, run:\n\n\`\`\`\npnpm gym review-score --pr <this PR number>\n\`\`\``,
      );

      await writeFile(
        path.join(REVIEW_MODE_DIR, "my-review.md"),
        `# My Review — Tier ${tier}: ${topic}\n\n` +
          `This exercise was opened as [PR #${pr.number}](${pr.url}). Leave your review comments directly ` +
          "on the PR, then run:\n\n```\npnpm gym review-score --pr " +
          `${pr.number}\n\`\`\`\n\n` +
          `(This file is a local copy for reference; grading reads from the GitHub PR, not from here.)\n`,
      );

      console.log(`Exercise written to ${REVIEW_MODE_DIR}/latest-exercise.tsx`);
      console.log(`Opened PR #${pr.number}: ${pr.url}`);
      console.log(`Review it on GitHub, then run: pnpm gym review-score --pr ${pr.number}`);
    });
}
